// Generated by ChatGPT

import XCTest
@testable import HN_Lens

import XCTest

class StringInsertTests: XCTestCase {
    func testEmptyInput() {
        let input = ""
        let expectedOutput = ""
        XCTAssertEqual(input.insert(string: "\n"), expectedOutput)
    }

    func testInputWithLessThanStrideLength() {
        let input = "Hello"
        let expectedOutput = "Hello"
        XCTAssertEqual(input.insert(string: "\n"), expectedOutput)
    }

    func testInputWithExactlyStrideLength() {
        let input = "abcdef"
        let expectedOutput = "abcdef"
        XCTAssertEqual(input.insert(string: "\n"), expectedOutput)
    }

    func testInputWithMoreThanStrideLength() {
        let input = "abcdefgh"
        let expectedOutput = "abcdef\ngh"
        XCTAssertEqual(input.insert(string: "\n"), expectedOutput)
    }

    func testInputWithMultipleOfStrideLength() {
        let input = "abcdefghijklmnopqrstuvwxyz"
        let expectedOutput = "abcdef\nghijkl\nmnopqr\nstuvwx\nyz"
        XCTAssertEqual(input.insert(string: "\n"), expectedOutput)
    }
    
    func testInputWithStrideOfFive() {
        let input = "abcdefghijklmnopqrstuvwxyz"
        let expectedOutput = "abcde\nfghij\nklmno\npqrst\nuvwxy\nz"
        XCTAssertEqual(input.insert(string: "\n", stride: 5), expectedOutput)
    }
}
